### ISSUE TITLE
how to install in an online linux VPS

### ISSUE THREAD

**Issue by creedexchange** [HydroProtocol/hydro-scaffold-dex#36]
how to install in an online linux VPS

how to install in an online linux VPS

I only see the local d option

**Comment by kevinxzhang** [comment]
hi creedexchange, 
if you install fail, please show the os version & show your install command & some install logs.

**Comment by kevinxzhang** [comment]
@creedexchange 
to install other network, see [(https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/change-network-and-run-from-source.md)]

**Comment by o-ayoub** [comment]
Hello, I have install it on vps ubuntu 16.04.
it shows this error on console;

![it_does_not](https://user-images.githubusercontent.com/27408905/57807680-2c40a080-7751-11e9-9135-2b9e1ef4d128.png)

When I do this on url bar: 
http://vpsip:3001/markets
it works:
and gives this: 
![it](https://user-images.githubusercontent.com/27408905/57807795-6dd14b80-7751-11e9-9daf-deab01db4a15.png)

Please how can I fix it ?

**Comment by mingmin-ddex** [comment]
> Hello, I have install it on vps ubuntu 16.04.
> it shows this error on console;
> 
> ![it_does_not](https://user-images.githubusercontent.com/27408905/57807680-2c40a080-7751-11e9-9135-2b9e1ef4d128.png)
> 
> When I do this on url bar:
> http://vpsip:3001/markets
> it works:
> and gives this:
> ![it](https://user-images.githubusercontent.com/27408905/57807795-6dd14b80-7751-11e9-9daf-deab01db4a15.png)
> 
> Please how can I fix it ?

hi, @o-ayoub check out this guide to make the dex reachable on VPS:

https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/config-nginx.md

**Comment by o-ayoub** [comment]
Thank you @mingmin-ddex , I have finally installed the script, But I have this error on console; when I run docker-compose up -d
![toto_](https://user-images.githubusercontent.com/27408905/57827430-d5f65080-7796-11e9-8aa3-b319a6bd7bcf.png)

And also this: 
![titi](https://user-images.githubusercontent.com/27408905/57827459-f45c4c00-7796-11e9-81d2-e8fd2e026e5b.png)


Thanks

**Comment by davidqhr** [comment]
@o-ayoub The error in your web console is about wallet-connect. It is a known issue and it will be fixed in the feature.

**Comment by o-ayoub** [comment]
Thank you @GongDDEX .

**Comment by o-ayoub** [comment]
Hello, how we can update css styles ?

**Comment by davidqhr** [comment]
The css codes are in web dir.
