### ISSUE TITLE
error when an order cancel twice

### ISSUE THREAD

**Issue by kevinxzhang** [HydroProtocol/hydro-scaffold-dex#38]
error log
`{"time":"2019-05-15T04:19:27.959111553Z","level":"INFO","prefix":"-","file":"orderbook.go","line":"327","message":"plItem is nil when RemoveOrder"}`

**Comment by davidqhr** [comment]
@kevinxzhang Can we close this now? Is it fixed?

**Comment by kevinxzhang** [comment]
> @kevinxzhang Can we close this now? Is it fixed?

It was fixed.
