### ISSUE TITLE
VPS Requirements 

### ISSUE THREAD

**Issue by o-ayoub** [HydroProtocol/hydro-scaffold-dex#39]
Hello, 
What is it VPS Requirement to have this script runing perfectly?
Currently I have a vps with configs below:

![cp](https://user-images.githubusercontent.com/27408905/57903646-7d8a8600-785e-11e9-883d-59c20d2a82c9.png)

when I do: docker-compose pull && docker-compose up -d 

it shows in console that some service does not load: out of memory. 

Thanks

**Comment by mingmin-ddex** [comment]
can you post more logs about the error?

**Comment by malisting** [comment]
I also it shows me  a blank page for logs I see no logs

**Comment by o-ayoub** [comment]
@mingmin-ddex, 
![this_is_it](https://user-images.githubusercontent.com/27408905/57951504-c03d7400-78d9-11e9-8f60-b69a0456100c.png)

**Comment by o-ayoub** [comment]
@malisting  
Hello, did you fix it ?

**Comment by kevinxzhang** [comment]
@o-ayoub
hi, o-ayoub
maybe the memory of your docker deamon is not enough on your vps.
you can show the memory config with run commond `docker info`.
your docker deamon need at least 500M memory.

**Comment by o-ayoub** [comment]
@kevinxzhang Thank you. Yes, the memory is not enough.
