### ISSUE TITLE
Error during docker build

### ISSUE THREAD

**Issue by o-ayoub** [HydroProtocol/hydro-scaffold-dex#40]
Hello, I got this error when I do docker build .
![toto](https://user-images.githubusercontent.com/27408905/57978349-a300c680-79fb-11e9-9c03-c0294743e1ed.png)

**Comment by kevinxzhang** [comment]
@o-ayoub 
hi o-ayoub
if you want build project from source, make sure the compiler environment has enough memory.

**Comment by o-ayoub** [comment]
Oh yes, that is it. The only way to change and update css file, is to update web folder and build the new image, also change image in  docker-compose.yml.

Thanks
