### ISSUE TITLE
Opening Web folder // npm install/run/start no visual Reacg

### ISSUE THREAD

**Issue by walter-grace** [HydroProtocol/hydro-scaffold-dex#43]
When trying to run on react I am having issues getting the graphic up in the browser, nothing is coming up on deploying it. It says complied successfully, but nothing is coming up. I tried uninstalling, do I need to docker everything first like in the opening read.me? Maybe I am missing something?

**Comment by davidqhr** [comment]
Please provide some debug infos such as browser console logs, docker logs. Then I can help.

**Comment by walter-grace** [comment]
Here is what is in my console for React;
<img width="539" alt="Screen Shot 2019-07-04 at 7 57 12 AM" src="https://user-images.githubusercontent.com/31444892/60675558-84328400-9e31-11e9-81e5-5909ddbedd8d.png">
Hope this helps

**Comment by davidqhr** [comment]
I think it's because you the app can't get correct result from node. Are you using localhost ethereum node? If so, have you switched your rpc network to localhost:8545?
