### ISSUE TITLE
Error while trying to approve a market pair | Error -32602

### ISSUE THREAD

**Issue by hardx4** [HydroProtocol/hydro-scaffold-dex#44]
I am using the command `docker-compose -f docker-compose-mainnet.yaml up -d` to start the exchange.

I have the NIO-BNB pair added according to the image:
![image](https://user-images.githubusercontent.com/7688208/60389286-12eb7d80-9a8d-11e9-8abd-f431e673237d.png)

When I try to run the command `hydro-dex-ctl market approve NIO-BNB` the following error occurs:

> {
  "desc": "Error -32602 (invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes)",
  "status": -1
}

![image](https://user-images.githubusercontent.com/7688208/60389308-53e39200-9a8d-11e9-840d-f001fdb6f402.png)

The same when I try to publish by running the command `hydro-dex-ctl market publish NIO-BNB`
![image](https://user-images.githubusercontent.com/7688208/60389334-a4f38600-9a8d-11e9-9394-fa44ffca3e81.png)

Can anyone help?

**Comment by davidqhr** [comment]
It seem one of the hex length is wrong. Please check if all the ethereum address you used in both db and envs are correct.

**Comment by hardx4** [comment]
> 
> 
> It seem one of the hex length is wrong. Please check if all the ethereum address you used in both db and envs are correct.

Thanks buddy, I managed to approve now, but when access to exchange, does not appear in the list of tokens the market approved.

![image](https://user-images.githubusercontent.com/7688208/60635048-368d2b80-9ddf-11e9-82ec-53e1520b84f0.png)

I've successfully passed NIO-WETH pair approval, but the NIO token does not appear in the token list.

**Comment by davidqhr** [comment]
It's seem you have already made some trades.https://hydroscan.io/relayers/0xdcf66476A97e9F623f1Bba315e131173b0e95b69.
 Have you solved it?

**Comment by hardx4** [comment]
I spent a whole day trying to figure out the problem, and searching the internet found an answer in which the user informed me that the error with CORS was not happening with chrome, so I did the test, and to my surprise the reading of the tokens works in chrome , in firefox does not work, any ideas?

One solution was to downgrade the version of web3: https://github.com/INFURA/infura/issues/57 and here https://ethereum.stackexchange.com/questions/60509/cors-error-with-infura

Response Headers on Chrome:
![image](https://user-images.githubusercontent.com/7688208/60725091-350a5300-9f06-11e9-90b2-1eb792eb7c1b.png)

Response Headers on Firefox:
![image](https://user-images.githubusercontent.com/7688208/60725128-49e6e680-9f06-11e9-9d05-95b83b57c527.png)

There is a problem with the watcher module too, it crashes constantly during its execution:
![image](https://user-images.githubusercontent.com/7688208/60725453-0fca1480-9f07-11e9-9bca-7159293f3f16.png)

When this happens the moment he will confirm a sale or a purchase, even if it restarts as it always does, the order stays in status waiting forever.

Another problem I noticed was that even on localhost or mainnet, the graph is not populated. although there have been purchases and sales, remains zero. Any possible solution to this?

![image](https://user-images.githubusercontent.com/7688208/60725927-4a807c80-9f08-11e9-9c7f-d7fe415c1a82.png)

**Comment by kevinxzhang** [comment]
@hardx4 
> When this happens the moment he will confirm a sale or a purchase, even if it restarts as it always does, the order stays in status waiting forever.

It heppends when the block number of your watcher (local block number) is bigger than the block number of ethereum-node.  

You can find the block number on your local redis server with key `HYDRO_WATCHER_BLOCK_NUMBER_CACHE_KEY`，and edit 
 it manually.

In normal, local block number is always equal or less than ethereum-node block number .

> Another problem I noticed was that even on localhost or mainnet, the graph is not populated. although there have been purchases and sales, remains zero. Any possible solution to this?

It is a bug, and it will be fixed soon.

**Comment by hardx4** [comment]
@kevinxzhang 
I did not solve the crash, but I edited the watch module to save the block number before the stopping point in a text file, when it stops and returns, I read this file, I'm going to check this key in the redis, thank you .

As for the graph that did not work, there is a timestamp commented on in the watch module, I assigned a timestamp, then the executed orders were left with correct time, and the graph started to work.

From what I've seen, seem to have settled, on a recent commit.
