### ISSUE TITLE
error when trying to create a market

### ISSUE THREAD

**Issue by halflifecode** [HydroProtocol/hydro-scaffold-dex#47]
when I try to create a market for HOT-BOMB using the following code:

> / #  hydro-dex-ctl market new HOT-BOMB \
>    --baseTokenAddress=0x4c4fa7e8ea4cfcfc93deae2c0cff142a1dd3a218 \
>    --quoteTokenAddress=0x1C95b093d6C236d3EF7c796fE33f9CC6b8606714
cannot find Symbol by address 0x1c95b093d6c236d3ef7c796fe33f9cc6b8606714 on chain

I get the error that the hydrosdk cannot find the symbol by address on chain.

I get this same error no matter what erc20 token I try to add.

**Comment by halflifecode** [comment]
The problem was that the demo isn't connected to the ether mainnet. You must run "docker-compose -f docker-compose-mainnet.yaml up" to connect to the ether mainnet.

**Comment by ductridev** [comment]
Do I need to update mainnet api url to new api url ?
