### ISSUE TITLE
Go Error when trying to follow instructions in setup-dev-env.md

### ISSUE THREAD

**Issue by halflifecode** [HydroProtocol/hydro-scaffold-dex#48]
I get an error when trying to "make api". I think its related to my go env variables or path being incorrect. Can anyone shed some light on this? I have uploaded a photo of the error below.

Thank you.
Rachel

https://imgur.com/a/3h9jfq2

**Comment by davidqhr** [comment]
Try golang version >= 1.10

**Comment by halflifecode** [comment]
>go version
>go version go1.6.2 linux/amd64

When I type "go version" this is the output I get. Is that satisfactory?

**Comment by davidqhr** [comment]
No, try to upgrade your golang version.
