### ISSUE TITLE
Weth disabled on UI

### ISSUE THREAD

**Issue by halflifecode** [HydroProtocol/hydro-scaffold-dex#49]
I have created a NUKER-WETH market, and I have approved it. Nuke is approved in my wallet in the UI, but WETH isn't. Why is this?

https://imgur.com/a/z2mKYlg

**Comment by davidqhr** [comment]
The admin cli approval is for the relayer address, not the one you are using in browser. I guess the relayer address and the one in browser is not the same address, right? As a user, you have to approve WETH independently before buying.
