### ISSUE TITLE
API's order service ignores order type

### ISSUE THREAD

**Issue by jie85** [HydroProtocol/hydro-scaffold-dex#50]
The functions of backend/api/orders_server.go  ignore the order type. These functions assume that the amount is in base token. However, when the type of order is “market” and the side is "buy", the amount of order is in quote token.

However MatchOrder() of orderbook.go deals with the "market" order correctly.

**Comment by davidqhr** [comment]
In our market order design, since there isn't a price, we think you should only care about how many assets you are will to spend to trade. So If the order side is buy, you need to provide quote token amout. If the order side is sell, you need to provide base token amount.
