### ISSUE TITLE
Blank page?

### ISSUE THREAD

**Issue by joek899** [HydroProtocol/hydro-scaffold-dex#52]
After running docker-compose pull && docker-compose up -d
i tried to check out the exchange by visiting http://165.22.121.237:3000 but i only see blank page, what do i do to see exchange?

**Comment by 1Eskor** [comment]
having the same issue as well, I believe it has to do with the port forwarding. I am using a Mac, any help regarding this would be appreciated

**Comment by davidqhr** [comment]
Can you provide some browser logs and the docker-compose logs?

**Comment by joek899** [comment]
> 
> 
> Can you provide some browser logs and the docker-compose logs?

according to the guide 

> docker-compose pull && docker-compose up -d
> 
> This step may takes a few minutes. When complete, it will start all necessary services.
> 
> It will use ports 3000, 3001, 3002, 6379, 8043, and 8545 on your computer. Please make sure theses ports are available.
> 
> Check out your relayer
> 
> Open http://localhost:3000/ on your browser to see your exchange in action!

 
But after this step it doesn't display the exchange why is this happening?
![hydrodexwhy](https://user-images.githubusercontent.com/54022044/63210188-23aa8e00-c0e3-11e9-9cd0-5bcecf4fc50f.jpg)

**Comment by joek899** [comment]
Chrome logs ![hydrowhy2](https://user-images.githubusercontent.com/54022044/63210201-59e80d80-c0e3-11e9-850a-759196d8d6a5.jpg)

**Comment by joek899** [comment]
The guide says after the third step exchange should be live what could be wrong?

**Comment by davidqhr** [comment]
I think you configured the wrong envs. Your frontend server is listening http://165.22.121.237:3000. But the frontend web page is still requesting backend api at `http://localhost:3001/`. You can follow the nginx manual to configure external access.
https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/config-nginx.md

**Comment by 1Eskor** [comment]
<img width="761" alt="Screen Shot 2019-08-19 at 7 12 52 PM" src="https://user-images.githubusercontent.com/44993492/63305603-83f12980-c2b5-11e9-8d9c-ccd0d156a234.png">

**Comment by joek899** [comment]
> 
> 
> I think you configured the wrong envs. Your frontend server is listening http://165.22.121.237:3000. But the frontend web page is still requesting backend api at `http://localhost:3001/`. You can follow the nginx manual to configure external access.
> https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/config-nginx.md

I followed the steps as outlined in the guide i did not do anything different, so the guide is telling us to follow wrong steps? You should update the guide?

**Comment by davidqhr** [comment]
> > I think you configured the wrong envs. Your frontend server is listening http://165.22.121.237:3000. But the frontend web page is still requesting backend api at `http://localhost:3001/`. You can follow the nginx manual to configure external access.
> > https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/config-nginx.md
> 
> I followed the steps as outlined in the guide i did not do anything different, so the guide is telling us to follow wrong steps? You should update the guide?

You mean you are running a nginx as the reverse proxy? If so, you should access your dex from 80 port, not 3000. If you can provide an online demo, I can help you to investigate.
