### ISSUE TITLE
fcntl64: symbol not found

### ISSUE THREAD

**Issue by jspedros** [HydroProtocol/hydro-scaffold-dex#53]
Getting the following errors:

hydro-scaffold-dex-launcher | Error relocating /bin/launcher: fcntl64: symbol not found
hydro-scaffold-dex-engine | Error relocating /bin/engine: fcntl64: symbol not found
hydro-scaffold-dex-admin-api | Error relocating /bin/adminapi: fcntl64: symbol not found
hydro-scaffold-dex-watcher | Error relocating /bin/watcher: fcntl64: symbol not found
hydro-scaffold-dex-api | Error relocating /bin/api: fcntl64: symbol not found

Logs attached:
[log.txt](https://github.com/HydroProtocol/hydro-scaffold-dex/files/3519069/log.txt)

**Comment by jspedros** [comment]
As a workaround, using the _frolvlad/alpine-glibc_ base image and recreating the images from source seems to be working fine.

**Comment by davidqhr** [comment]
Hi, thanks for the info. Will look into it.

**Comment by jspedros** [comment]
As a workaround, using an alpine docker base image with glibc installed seems to work fine.

**Comment by davidqhr** [comment]
Solved it by installing glibc in the alpine image. Docker image is also updated on docker hub.
