### ISSUE TITLE
Docker is exposing an unsecured redis service (port 6379) to the outside

### ISSUE THREAD

**Issue by jspedros** [HydroProtocol/hydro-scaffold-dex#54]
Docker is exposing an unsecured redis service (port 6379) to the outside. Most of the images are exposing ports to the world outside Docker when this may not be necessary. This is a security issue if not using a firewall.

![image](https://user-images.githubusercontent.com/6378927/63491871-9a1b0780-c4b8-11e9-82a0-ab2175f13d50.png)

Recommend changing _ports_ to _expose_ in _docker-compose.yaml_ for images that don't need to be accessed from outside Docker.

_image: redis:5.0
  expose:
    - 6379_

**Comment by davidqhr** [comment]
Thanks, I will look into this.

**Comment by davidqhr** [comment]
Now the services are only exposed to the localhost network. The docker-compose way is just a convenience for demo purposes. For anyone using hydro scaffold dex, it's not commended to deploy directly with the default docker compose file.
