### ISSUE TITLE
Add hydro margin feature

### ISSUE THREAD

**Issue by codingalex** [HydroProtocol/hydro-scaffold-dex#60]

**Comment by davidqhr** [comment]
Hydro Protocol has two major versions. For version 1, it's designed for noncustodial token exchange. Hydro dex scaffold is build on top of this version contract.

For version 2, it's a custodial exchange, funding, and margin protocol. The two versions have significent different. We don't have a plan to upgrade the scaffold dex to support version 2 contract. 

Thank you for your interest in our project. We will post if we have some arrangements of hydro scaffold things on top of hydro protocol contract version 2.
