### ISSUE TITLE
Changes to Hydro SDK Web frontend not reflecting

### ISSUE THREAD

**Issue by naijarace** [HydroProtocol/hydro-scaffold-dex#62]
I am unable to customize the frontend of the Hydro SDK Web. I tried changing the hydro logo to my logo, the header title to mine and some other changes but it doesn't reflect the changes. Any changes I make using an editor doesn't reflect on the live SDK. Please help

**Comment by bqdplqn** [comment]
https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/setup-dev-env.md

**Comment by davidqhr** [comment]
I think you need to run the development environment to see the changes in time. Thanks @Nawrasnetwork .
