### ISSUE TITLE
No direct link for listed tokens

### ISSUE THREAD

**Issue by naijarace** [HydroProtocol/hydro-scaffold-dex#63]
Tokens listed on the exchange are supposed to have a direct link. e.g https://example.com/trade/WETH-DAI but the sdk only has the default homepage https://example.com for all tokens. Please can this be fixed? It's it's available do tell how i can fix it. Thank you

**Comment by davidqhr** [comment]
This can be done by adding a router library in web project. We don't want to do too many decisions for users, and we want keep this repo easy to customize. I think you can take a look at https://github.com/supasate/connected-react-router.
