### ISSUE TITLE
Can this exchange be used for other cryptocurrency transactions such as BTC

### ISSUE THREAD

**Issue by a20180502** [HydroProtocol/hydro-scaffold-dex#66]
Can we add transaction pairs such as USD and euro

**Comment by davidqhr** [comment]
Hydro Protocol is only working on Ethereum ecosystem. Unfortunately, It doesn't support BTC.

But it supports all the erc20 tokens and ether. You may want to take a look at
https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/admin-api-and-cli.md#create-a-new-market
