### ISSUE TITLE
Not able to view after compile

### ISSUE THREAD

**Issue by JimboReddJones** [HydroProtocol/hydro-scaffold-dex#75]
After compiling the source code with docker-compose -f docker-compose-mainnet-source.yaml up

i tried to connect to http://My.ip/3000 and i get a blank layout

![image](https://user-images.githubusercontent.com/35225336/74085650-9a658a00-4a7b-11ea-865d-97cd69769fd1.png)

and this is what it says also 

![image](https://user-images.githubusercontent.com/35225336/74085719-5b840400-4a7c-11ea-9cf3-93472c9e350e.png)

**Comment by kevinxzhang** [comment]
> After compiling the source code with docker-compose -f docker-compose-mainnet-source.yaml up
> 
> i tried to connect to http://My.ip/3000 and i get a blank layout
> 
> ![image](https://user-images.githubusercontent.com/35225336/74085650-9a658a00-4a7b-11ea-865d-97cd69769fd1.png)
> 
> and this is what it says also
> 
> ![image](https://user-images.githubusercontent.com/35225336/74085719-5b840400-4a7c-11ea-9cf3-93472c9e350e.png)

hi JimboReddJones, it looks like an error when starting web with env.sh. Have you ever do some edit in env.sh?

**Comment by Belifex** [comment]
No edit has been made. When deployment of the demo version it all runs smooth, when deployment occurred for the mainnet, it doesnt show

**Comment by JimboReddJones** [comment]
Nothing had been changed on the env.sh file in the web folder

**Comment by kevinxzhang** [comment]
Maybe due to a newline character.

**Comment by JimboReddJones** [comment]
![Screenshot_20200211-102843~2](https://user-images.githubusercontent.com/35225336/74224788-c40bf480-4cb9-11ea-8f91-ca370ef86c61.png)

**Comment by JimboReddJones** [comment]
This is the output of that command

**Comment by kevinxzhang** [comment]
Could you run  ```docker-compose exec web  /bin/cat -e env.sh``` after run  ```docker-compose -f docker-compose-mainnet-source.yaml up``` to see env.sh file in docker
