### ISSUE TITLE
Error, white screen, and exiting code 2

### ISSUE THREAD

**Issue by justanthonyofficial** [HydroProtocol/hydro-scaffold-dex#76]
Help with a mistake. Here is such an error and a white screen instead of the exchange
![photo_2020-02-22_18-13-16](https://user-images.githubusercontent.com/56980860/75097125-5624ce80-55d1-11ea-984d-6e3e7ca48818.jpg)

**Comment by MonarthS** [comment]
#80

**Comment by MonarthS** [comment]
Duplicate of #80

**Comment by tstyle11** [comment]
Closing as fixed
