### ISSUE TITLE
Connection refused error while setting up Dex on localhost

### ISSUE THREAD

**Issue by Dimple-Kanwar** [HydroProtocol/hydro-scaffold-dex#78]
I am following the instructions mentioned in the link: 
https://hydroprotocol.io/docs/overview/getting-started.html
After executing "docker-compose pull && docker-compose up -d", when I am trying to access localhost:3000 in browser, I am getting connection refused error in browser console 

when i try to manually configure ,I am getting following error in on executing make api:

go run ./cli/api/main.go
panic: dial tcp 127.0.0.1:5432: connect: connection refused

goroutine 1 [running]:
github.com/HydroProtocol/hydro-scaffold-dex/backend/models.Connect(0xc0000342e1, 0x3f, 0xc0000342e1)
	/home/dimple/blockchain/hydro/hydro-scaffold-dex/backend/models/conn.go:16 +0x105
github.com/HydroProtocol/hydro-scaffold-dex/backend/api.StartServer(0xd5a800, 0xc0000371c0, 0xca4090)
	/home/dimple/blockchain/hydro/hydro-scaffold-dex/backend/api/server.go:139 +0x112
main.run(0xc00002a118)
	/home/dimple/blockchain/hydro/hydro-scaffold-dex/backend/cli/api/main.go:16 +0x97
main.main()
	/home/dimple/blockchain/hydro/hydro-scaffold-dex/backend/cli/api/main.go:22 +0x22
exit status 2
Makefile:14: recipe for target 'api' failed
make: *** [api] Error 1

I am using ubuntu 18.04 version for its deployment.

could you please help in resolving this error? In case of any modification required, please do let me know to run this properly.

**Comment by tstyle11** [comment]
Closing as fixed
