### ISSUE TITLE
Name site

### ISSUE THREAD

**Issue by irish0321** [HydroProtocol/hydro-scaffold-dex#79]
Hello. Can i know how to change the name of the website i create using your platform ?

**Comment by tstyle11** [comment]
Sure the entire front-end is open source, so you can change whatever you want.

Let's say you wanted to change the logo, then you would change https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/web/src/components/Header/index.js (search for 'hydro.svg' and replace with your own)
