### ISSUE TITLE
White page and Docker does not load files

### ISSUE THREAD

**Issue by forwelldj** [HydroProtocol/hydro-scaffold-dex#80]
Hello guys I would like to take some questions.
I did this tutorial correctly:
"Launch a DEX on your local server
Once you have docker installed, open up your terminal and enter the following commands:

Clone the git repository

 git clone https://github.com/hydroprotocol/hydro-scaffold-dex.git
Change your working directory

 cd hydro-scaffold-dex
Build and Launch your Hydro Relayer

 docker-compose pull && docker-compose up -d
This step downloads all of the required environments and files for the standard Hydro Relayer. After all of the files are prepared, it will launch the relayer to your local server (localhost: 3000). It could take a few minutes to complete. "

But when I send the command "docker-compose pull && docker-compose up -d" in CMD and go to localhost: 3000 me from the white screen, only the icon and the name Hydro SDK Web in the tab appears, the rest is all white, at Docker the hydro-scaffold-dex-makerhydroprotocolio / amm-bots is restarting and sometimes it appears as EXITED (2).

LOG: /amm-bots/main.go:16 + 0x70
panic: Get http: // api: 3001 / markets: dial tcp 172.18.0.9:3001: connect: connection refused

and hydro-scaffold-dex-pgpostgres
RESTARTING

LOG: https://www.postgresql.org/docs/current/auth-trust.html

Error: Database is uninitialized and superuser password is not specified.

You must specify POSTGRES_PASSWORD to a non-empty value for the

superuser. For example, "-e POSTGRES_PASSWORD = password" on "docker run".

You may also use "POSTGRES_HOST_AUTH_METHOD = trust" to allow all

connections without a password. This is * not * recommended.

See PostgreSQL documentation about "trust":

![Esboço01](https://user-images.githubusercontent.com/42697257/76019836-a7fb1c00-5f22-11ea-8633-4f7fef4c8089.png)
![Esboço02](https://user-images.githubusercontent.com/42697257/76019841-a92c4900-5f22-11ea-9b50-bd88727bfcc3.png)
![Esboço03](https://user-images.githubusercontent.com/42697257/76019844-a9c4df80-5f22-11ea-9798-12d95b750fe9.png)

**Comment by Slambambam** [comment]
Same story!

**Comment by forwelldj** [comment]
> Same story!

Did you do the same steps as the site? I even bought a VPS to try and make the same mistake

**Comment by pironmind** [comment]
Hello is config files is correct?

**Comment by forwelldj** [comment]
> Hello is config files is correct?

Hello, what files do you say ?

**Comment by MonarthS** [comment]
You have to add `POSTGRES_PASSWORD` environment variable in `docker-compose.yaml` file:
```
environment:
      POSTGRES_PASSWORD: "postgres"
```

**Comment by jobinpankajan** [comment]
> You have to add `POSTGRES_PASSWORD` environment variable in `docker-compose.yaml` file:
> 
> ```
> environment:
>       POSTGRES_PASSWORD: "postgres"
> ```

Which line of this file ?

**Comment by jobinpankajan** [comment]
> Hello guys I would like to take some questions.
> I did this tutorial correctly:
> "Launch a DEX on your local server
> Once you have docker installed, open up your terminal and enter the following commands:
> 
> Clone the git repository
> 
>  git clone https://github.com/hydroprotocol/hydro-scaffold-dex.git
> Change your working directory
> 
>  cd hydro-scaffold-dex
> Build and Launch your Hydro Relayer
> 
>  docker-compose pull && docker-compose up -d
> This step downloads all of the required environments and files for the standard Hydro Relayer. After all of the files are prepared, it will launch the relayer to your local server (localhost: 3000). It could take a few minutes to complete. "
> 
> But when I send the command "docker-compose pull && docker-compose up -d" in CMD and go to localhost: 3000 me from the white screen, only the icon and the name Hydro SDK Web in the tab appears, the rest is all white, at Docker the hydro-scaffold-dex-makerhydroprotocolio / amm-bots is restarting and sometimes it appears as EXITED (2).
> 
> LOG: /amm-bots/main.go:16 + 0x70
> panic: Get http: // api: 3001 / markets: dial tcp 172.18.0.9:3001: connect: connection refused
> 
> and hydro-scaffold-dex-pgpostgres
> RESTARTING
> 
> LOG: https://www.postgresql.org/docs/current/auth-trust.html
> 
> Error: Database is uninitialized and superuser password is not specified.
> 
> You must specify POSTGRES_PASSWORD to a non-empty value for the
> 
> superuser. For example, "-e POSTGRES_PASSWORD = password" on "docker run".
> 
> You may also use "POSTGRES_HOST_AUTH_METHOD = trust" to allow all
> 
> connections without a password. This is * not * recommended.
> 
> See PostgreSQL documentation about "trust":
> 
> ![Esboço01](https://user-images.githubusercontent.com/42697257/76019836-a7fb1c00-5f22-11ea-8633-4f7fef4c8089.png)
> ![Esboço02](https://user-images.githubusercontent.com/42697257/76019841-a92c4900-5f22-11ea-9b50-bd88727bfcc3.png)
> ![Esboço03](https://user-images.githubusercontent.com/42697257/76019844-a9c4df80-5f22-11ea-9798-12d95b750fe9.png)

The same issue i have, did you solve it ?

**Comment by tstyle11** [comment]
Closing this issue as fixed.
