### ISSUE TITLE
White page is what i get after going to localhost:3000

### ISSUE THREAD

**Issue by kowski007** [HydroProtocol/hydro-scaffold-dex#81]
It seem this is the issue most of us are facing using this deploying the dex - pls, kindly help us fix this.

**Comment by Ishu1998** [comment]
I am facing the same issue

**Comment by ian-p-johnson** [comment]
Same thing on Chrome, Brave, Edge explorer - blank page - title on tab on top of browser only

View Source shows following (Shields down on Brave)


<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="/favicon.png"/><link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><title>Hydro SDK Web</title><link href="/static/css/font-awesome@4.7.0.css" rel="stylesheet"/><link rel="stylesheet" href="/static/css/bootstrap@4.3.1.css"/><script src="/static/js/jquery@3.3.1.js"></script><script src="/static/js/popper@1.14.7.js"></script><script src="/static/js/bootstrap@4.3.1.js"></script><script src="/static/js/reconnecting-websocket@1.0.0.js"></script><script type="text/javascript" src="/config.js?v=1595720889"></script><link href="/static/css/2.331fc237.chunk.css" rel="stylesheet"><link href="/static/css/main.9d113218.chunk.css" rel="stylesheet"></head><body><div id="root"></div><script>!function(l){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],f=0,i=[];f<n.length;f++)t=n[f],p[t]&&i.push(p[t][0]),p[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(l[r]=o[r]);for(s&&s(e);i.length;)i.shift()();return c.push.apply(c,u||[]),a()}function a(){for(var e,r=0;r<c.length;r++){for(var t=c[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==p[u]&&(n=!1)}n&&(c.splice(r--,1),e=f(f.s=t[0]))}return e}var t={},p={1:0},c=[];function f(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return l[e].call(r.exports,r,r.exports,f),r.l=!0,r.exports}f.m=l,f.c=t,f.d=function(e,r,t){f.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},f.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},f.t=function(r,e){if(1&e&&(r=f(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(f.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)f.d(t,n,function(e){return r[e]}.bind(null,n));return t},f.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return f.d(r,"a",r),r},f.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},f.p="/";var r=window.webpackJsonp=window.webpackJsonp||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;a()}([])</script><script src="/static/js/2.053e78fd.chunk.js"></script><script src="/static/js/main.137fa06b.chunk.js"></script></body></html>
