### ISSUE TITLE
Does DDEX.io uses same protocol that is made available in Github ?

### ISSUE THREAD

**Issue by AKprisonER** [HydroProtocol/hydro-scaffold-dex#82]
ddex.io using same version or a different one ?

Lets say I want to start a decentralized exchange using HydraProtocol SDK. If i set it up under my website, can the users see trade histories that is made in DDex.io ?

Also is there any documentation to push it to a hosting provider?

**Comment by tstyle11** [comment]
Hi @AKprisonER 

Trade history is off-chain data stored in a postgres database. Each deployment of Hydro scaffold is by default isolated, and does not see trade histories made on ddex.io, or any other relayer.

Regarding documentation for deployment, for a quick ropsten staging server you can refer to [this guide](https://github.com/HydroProtocol/hydro-scaffold-dex/wiki/Tutorial:-how-to-run-Hydro-scaffold-on-a-$5-linode-Server) as a starting point. **However I would advise against using such rudimentary deployment schemes for production servers.**
