### ISSUE TITLE
借贷利率太不正常了

### ISSUE THREAD

**Issue by luyexunfeng** [HydroProtocol/hydro-scaffold-dex#83]
USDT借贷利率飙升到60%？这让人怎么借？才用了五六天就要赶紧还掉，加上手续费等，实际利率接近30%以上，谁还会再借？

**Comment by tstyle11** [comment]
Based on similar suggestions, there is a pending change to improve the interest rate curve to mitigate this issue: https://github.com/HydroProtocol/protocol/pull/15

For future reference. This is the repository for building a scaffod-dex, and the project does not have any lending related components. Please file future issues in HydroProtocol/protocol.
