### ISSUE TITLE
Problems related to database

### ISSUE THREAD

**Issue by jobinpankajan** [HydroProtocol/hydro-scaffold-dex#84]
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD to a non-empty value for the
superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

 lookup db on 127.0.0.11:53: no such host

**Comment by tstyle11** [comment]
hey @jobinpankajan thanks for finding this issue. I've submitted a PR with a simple one line fix.
